### ISSUE TITLE
No file to import FlightTickets.json 

### ISSUE THREAD

**Issue by venkatsaid** [sapph1re/flight-tickets#1]
In ./build/contracts there is no file names FlightTickets.json , but in app.js line 3 the file is used to import.

- It will be much helpful if there is any documentation regarding the project or explanation.

**Comment by sapph1re** [comment]
@venkatsaid There are some explanations in README.md. Did you do `truffle compile` as it is said in "How to run it"?

**Comment by venkatsaid** [comment]
![screenshot from 2019-01-22 15-27-13](https://user-images.githubusercontent.com/28043547/51527336-3cf3a080-1e5a-11e9-9293-dd6452dc07b6.png)

**> Failed to compile.
Error in ./src/App.js
Module not found: ../build/contracts/FlightTickets.json in /home/venkat_sai/bcprojects/flight-tickets-master/src
 @ ./src/App.js 18:21-69**

This is the problem I am facing. Is the file FlightTickets.json will be created automatically or do we need to create that file.

**Comment by sapph1re** [comment]
@venkatsaid How did your `truffle compile` go? Contracts are built during this operation. Did you do it?
